version: '2'
services:
  php-apache-dev:
    image: 'webdevops/php-apache-dev:7.2'
    links:
      - 'mysql:mysql'
    volumes:
      - '/Users/user/code/crud:/app'
    depends_on:
      - mysql
    ports:
      - '80:80'
      - '443:443'
      - '9000:9000'
    environment:
      - XDEBUG_REMOTE_AUTOSTART=1
      - XDEBUG_REMOTE_PORT=9000
      - WEB_DOCUMENT_ROOT=/app/web
  mysql:
    image: 'mysql:5.5'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=crud
    volumes:
      - './mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
